### ISSUE TITLE
v2.3　右上のオブジェクト変更ボタンのメニューが見切れる

### ISSUE THREAD

**Issue by nea-c** [amate/PropertyWindowFixerPlugin#1]
## 設定ダイアログが画面端でも、メニューがそのまま描画されて見切れる。

以下のようになります。
![image](https://user-images.githubusercontent.com/45559303/145264196-ef1221ba-fd1f-432a-9048-f0f5a7190181.png)

**Comment by amate** [comment]
v2.4で修正しました
