### ISSUE TITLE
[v2.3]メディアオブジェクトにショートカットキーでエフェクトをかける時の不具合

### ISSUE THREAD

**Issue by ousen1022** [amate/PropertyWindowFixerPlugin#2]
メディアオブジェクトにショートカットキーでエフェクトをかけようとすると、画像のように一覧がマウスカーソルの右下ではなく右上に表示されてしまい、見切れて選択できなくなります。
![bandicam 2021-12-28 13-13-07-705](https://user-images.githubusercontent.com/69716697/147527278-3af4579c-dc0b-4198-9dd2-b883bf267ac9.jpg)

**Comment by amate** [comment]
メディアオブジェクトにショートカットキーでエフェクトをかける方法が分からなかったので再現できませんでしたが、
v2.4で問題の部分を対処してみました
まだ問題が出るようならまたissueを立ててください
