### ISSUE TITLE
[v2.4]フィルタ効果入れ替え時に発生する描画バグ

### ISSUE THREAD

**Issue by ousen1022** [amate/PropertyWindowFixerPlugin#3]
v2.4において、スクロールをした状態でフィルタ効果の上下入れ替えを行うと、描画バグが発生します。
（#2のショートカットの問題は解消されました。ありがとうございます。）
![20211229 170216](https://user-images.githubusercontent.com/69716697/147641356-344e9a61-d6d6-4044-a901-055d76103261.png)

**Comment by amate** [comment]
再現しません
右クリックメニュー以外の方法(例えば他のプラグインなど)でフィルターの並び順を変更してますか？

**Comment by ousen1022** [comment]
右クリックで表示されるデフォルトの入れ替え機能で行いました。
何度か触っていると確定で発生する訳ではなく、体感ですがフィルタ効果のスライダーが4つ以上あるものを入れ替えた際によく発生しているように感じました。
また、折りたたみを行った際にも同じような表示の崩れが起こりました。
スクロールやウィンドウサイズの変更、別オブジェクトを選択したりすると、正常な画面が表示されるのを確認しています。

**Comment by amate** [comment]
フィルターの表示非表示で描画が乱れる問題が再現しましたので
v2.5で修正しました
